ktor:
  application:
    modules:
      - shhashi.practice.i20250126.ApplicationKt.module
  deployment:
    port: 8080
    watch:
      - classes
      - resources
jwt:
  secret: "ThisIsSecret"
