services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: service
      POSTGRES_PASSWORD: "abcD123"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 100s

    volumes:
      - ./docker/db/entrypoints:/docker-entrypoint-initdb.d

  db_builder:
    build:
      context: ./docker/db/builder
    environment:
      PGPASSWORD: "abcD123"
    depends_on:
      db:
        condition: service_healthy

